version: "3.3"

services:

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    networks:
    - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`ebms.myhops.com`) && Path(`/whoami`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

networks:
  web:
    external: true
