version: '2'

services:
  traefik:
    image: traefik:v2.0
    restart: always
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
    - web
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - etc-traefik:/etc/traefik
    container_name: traefik-ebms
    labels:
    # Dynamic Configuration
    labels:
    - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`) "
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.middlewares=auth"
    - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"

networks:
  web:
    external: true

volumes:
  etc-traefik:

