version: '3'

services:
  traefik:
    image: traefik:v2.0
    restart: always
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
    - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - etc-traefik:/etc/traefik
    container_name: traefik-ebms
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`ebms.myhops.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$IdE/lFD8$$9tDkinV0M3v2VqR6x8OPp1"

networks:
  web:
    external: true

volumes:
  etc-traefik:

