version: '2'

services:
  traefik:
    image: traefik:v2.0
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
    - web
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - etc-traefik:/etc/traefik
    container_name: traefik-ebms
    labels:
    # Dynamic Configuration
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.api.rule=rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.middlewares=auth"
    - "traefik.http.routers.api.tls"
    - "traefik.http.routers.api.tls.certresolver=myresolver"
    # - "traefik.http.routers.api.tls.domains.main=myhops.com"
    # - "traefik.http.routers.api.tls.domains.sans=ebms.myhops.com"
    - "traefik.http.middlewares.auth.basicauth.users=peza:$$apr1$$YjIRsK60$$x1RzbOoZKOxjfXVa4j3jz0"

networks:
  web:
    external: true

volumes:
  etc-traefik:

