# debug = false

# logLevel = "DEBUG"
# defaultEntryPoints = ["https","http"]

[api]
dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

# Enable ACME (Let's Encrypt): automatic SSL.
[certificatesResolvers.myresolver.acme]
  email = "peter.zandbergen@myhops.com"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"


[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = true
  swarmMode = false
  # defaultRule = "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

